vertical:
  cobblestone:
    buy: 500
    use: 5
  sand:
    buy: 500
    use: 5
  obsidian:
    buy: 1000
    use: 10

horizontal:
  cobblestone:
    buy: 500
    use: 0
    distance: 10
  obsidian:
    buy: 500
    use: 0
    distance: 10

#We should put a block after how many ticks
ticks: 10

